# Generated by Django 3.1.12 on 2025-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncHub', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
