# Generated by Django 3.1.12 on 2025-11-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20251112_0344'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE inventory_item ALTER COLUMN id DROP IDENTITY IF EXISTS;",
            reverse_sql="ALTER TABLE inventory_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
        ),
        migrations.RunSQL(
            "DROP SEQUENCE IF EXISTS inventory_item_id_seq;",
            reverse_sql="CREATE SEQUENCE inventory_item_id_seq OWNED BY inventory_item.id;"
        ),
    ]
