# Generated by Django 5.2.7 on 2025-11-03 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_login', '0002_officer_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='student_number',
            field=models.CharField(blank=True, help_text='Enter a unique 7-digit student number.', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Student number must be exactly 7 digits.')]),
        ),
    ]
