# Generated by Django 5.2.7 on 2025-11-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_login', '0003_alter_officer_student_number'),
    ]

    operations = [
    ]
