# Generated by Django 5.2.7 on 2025-11-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_login', '0004_auto_20251103_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='date',
            field=models.DateField(),
        ),
    ]
