# Generated by Django 5.2.7 on 2025-11-04 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_login', '0005_alter_timelog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='rfid_tag',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='student_number',
        ),
        migrations.AlterField(
            model_name='officer',
            name='id',
            field=models.CharField(help_text='Enter a unique 7-digit ID.', max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'ID must be exactly 7 digits.')]),
        ),
    ]
