# Generated by Django 3.1.12 on 2025-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_login', '0006_remove_officer_rfid_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
